import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const aktiv = localFont ({
    src: "../public/AktivGroteskEx_XBd.ttf",
    variable: "--font-aktiv",
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
    weight: ["600"],
});

export const metadata: Metadata = {
    title: "Yipper Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${aktiv.variable} antialiased`}
        >
            {children}
        </body>
        </html>
    );
}
